version: "3.9"

env_file: .env

services:
  minecraft:
    build: ./
    container_name: minecraft
    volumes:
      - ./container-files/build:/root/minecraft/build
      - ./container-files/server:/minecraft
      - ./container-files/minecraft:/opt/minecraft/
    expose:
      - "$JAVA_PORT"
      - "$BEDROCK_PORT"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
