version: "3.9"

env_file: .env

services:
  minecraft:
    build: ./
    container_name: minecraft
    volumes:
      - ./container-files/server:/minecraft/server
    ports:
      - "${JAVA_PORT}:${JAVA_PORT}/tcp"
      - "${BEDROCK_PORT}:${BEDROCK_PORT}/udp"
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
